### PR TITLE
Docker compose to setup FA and a admin user

### LINKED ISSUE #2: Setup docker-compose for FA
The setup should include FA deployed with a default username and password and an application setup.

See example [here](https://github.com/samagra-comms/docker-deploy/blob/main/docker-compose.yml#L394-L452). This should be merged with the issue #1.

### PR DESCRIPTION
**Pull request by tushar5526**
Closes #2 
On my local system, there were some issues when I was starting all the services together using `docker-compose up -d`. There were logs saying `cant able to get a lock on db` so I am starting each service with some buffer time for it to properly setup.

### CODE REVIEW

**Comment by ChakshuGautam** [comment]
Gitguadian is acting crazy on this. Let's remove secrets from sample.env. Just explain how to create those here in the doc.

**Comment by ChakshuGautam** [comment]
Add a readme to this as well.

**Comment by tushar5526** [comment]
I think I have to re-write my git history to remove the secrets from past commits. Is this needed ?

**Comment by ChakshuGautam** [comment]
Don't need to remove from the history. Just moving forward. It should not show in all the commits moving forward.

**Comment by tushar5526** [comment]
@ChakshuGautam Good to go!

**Pull request merged**
